### ISSUE TITLE
ASAP: You need to check one of your files

### ISSUE THREAD

**Issue by sm18lr88** [jmyissb/HealthLLM#1]
Check `CAFE_demo_release_ipynb.ipynb` for certain...private content... you should have deleted before uploading.

This was the only communication avenue I could find; there's no email addresses for private communication in your research paper.

**Comment by dev-err418** [comment]
No need to worry, when an OpenAI key is published on GitHub in plain text, it is deactivated by OpenAI...

**Comment by sm18lr88** [comment]
I'm pretty sure it wasn't deactivated, but glad it's not a concern.

Wish y'all the best. Good research.
